#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2024-07-28
# https://github.com/Aleksandr3Bocharov/RefalAB

mkdir -p bin
$REFALABBIN/RefalAB src/RefalABEinshteinPuzzle > RefalABEinshteinPuzzle.log
as -o src/RefalABEinshteinPuzzle.o src/RefalABEinshteinPuzzle.s >> RefalABEinshteinPuzzle.log
$REFALABBIN/RefalAB src/Solver >> RefalABEinshteinPuzzle.log
as -o src/Solver.o src/Solver.s >> RefalABEinshteinPuzzle.log
clang -o bin/RefalABEinshteinPuzzle src/RefalABEinshteinPuzzle.o src/Solver.o $REFALABLIB/mainrf.o -L$REFALABLIB -lRefalAB >> RefalABEinshteinPuzzle.log
bin/RefalABEinshteinPuzzle
