#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2025-10-17
# https://github.com/Aleksandr3Bocharov/refalabeinshteinpuzzle

RAYLIBCFLAGS="-Wall -O2"
RAYLIBLFLAGS="-lraylib -lm"

mkdir -p bin
$REFALABBIN/refalabc src/refalabeinshteinpuzzle_gui -a,"-o src/refalabeinshteinpuzzle_gui.o" > refalabeinshteinpuzzle_gui.log
$REFALABBIN/refalabc src/solver -a,"-o src/solver.o" >> refalabeinshteinpuzzle_gui.log
clang $REFALABCFLAGS -DPOSIX -I$REFALABINCLUDE -c src/refalabeinshteinpuzzlec_gui.c -o src/refalabeinshteinpuzzlec_gui.o >> refalabeinshteinpuzzle_gui.log
clang $RAYLIBCFLAGS -c src/gui.c -o src/gui.o >> refalabeinshteinpuzzle_gui.log
clang -o bin/refalabeinshteinpuzzle_gui src/refalabeinshteinpuzzle_gui.o src/refalabeinshteinpuzzlec_gui.o src/solver.o $REFALABLIB/obj/mainrf.o -L$REFALABLIB -lrefalab src/gui.o $RAYLIBLFLAGS >> refalabeinshteinpuzzle_gui.log
bin/refalabeinshteinpuzzle_gui
