#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2025-10-07
# https://github.com/Aleksandr3Bocharov/RefalAB

RAYLIBCFLAGS="-Wall -O2"
RAYLIBLFLAGS="-lraylib -lm"

mkdir -p bin
$REFALABBIN/RefalAB src/RefalABEinshteinPuzzle_gui > RefalABEinshteinPuzzle_gui.log
as -o src/RefalABEinshteinPuzzle_gui.o src/RefalABEinshteinPuzzle_gui.s >> RefalABEinshteinPuzzle_gui.log
$REFALABBIN/RefalAB src/Solver >> RefalABEinshteinPuzzle_gui.log
as -o src/Solver.o src/Solver.s >> RefalABEinshteinPuzzle_gui.log
clang $REFALABCFLAGS -DPOSIX -I$REFALABINCLUDE -c src/RefalABEinshteinPuzzlec_gui.c -o src/RefalABEinshteinPuzzlec_gui.o >> RefalABEinshteinPuzzle_gui.log
clang $RAYLIBCFLAGS -c src/gui.c -o src/gui.o >> RefalABEinshteinPuzzle_gui.log
clang -o bin/RefalABEinshteinPuzzle_gui src/RefalABEinshteinPuzzle_gui.o src/RefalABEinshteinPuzzlec_gui.o src/Solver.o $REFALABLIB/obj/mainrf.o -L$REFALABLIB -lRefalAB src/gui.o $RAYLIBLFLAGS >> RefalABEinshteinPuzzle_gui.log
bin/RefalABEinshteinPuzzle_gui
