#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2024-10-17
# https://github.com/Aleksandr3Bocharov/refalabeinsteinpuzzle

mkdir -p bin
$REFALABBIN/refalabc src/refalabeinsteinpuzzle -a,"-o src/refalabeinsteinpuzzle.o" > refalabeinsteinpuzzle.log
$REFALABBIN/refalabc src/solver -a,"-o src/solver.o" >> refalabeinsteinpuzzle.log
clang -o bin/refalabeinsteinpuzzle src/refalabeinsteinpuzzle.o src/solver.o $REFALABLIB/obj/mainrf.o -L$REFALABLIB -lrefalab >> refalabeinsteinpuzzle.log
bin/refalabeinsteinpuzzle
