#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2024-10-17
# https://github.com/Aleksandr3Bocharov/refalabeinshteinpuzzle

mkdir -p bin
$REFALABBIN/refalabc src/refalabeinshteinpuzzle -a,"-o src/refalabeinshteinpuzzle.o" > refalabeinshteinpuzzle.log
$REFALABBIN/refalabc src/solver -a,"-o src/solver.o" >> refalabeinshteinpuzzle.log
clang -o bin/refalabeinshteinpuzzle src/refalabeinshteinpuzzle.o src/solver.o $REFALABLIB/obj/mainrf.o -L$REFALABLIB -lrefalab >> refalabeinshteinpuzzle.log
bin/refalabeinshteinpuzzle
