#!/bin/sh 

# Copyright 2024 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2024-10-20
# https://github.com/Aleksandr3Bocharov/RefalAB

REFAL=/media/alexb/F/Programming/Projects/RefalAB

$REFAL/bin/RefalAB RefalABEinshteinPuzzle > RefalABEinshteinPuzzle.log
as -o RefalABEinshteinPuzzle.o RefalABEinshteinPuzzle.asm >> RefalABEinshteinPuzzle.log
clang -o RefalABEinshteinPuzzle $REFAL/lib/mainrf.o RefalABEinshteinPuzzle.o -Wl,-L$REFAL/lib -Wl,-lRefalAB >> RefalABEinshteinPuzzle.log
./RefalABEinshteinPuzzle
